/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Reservations = {
  _id: string;
  _type: "reservations";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  guestCount?: number;
  name?: string;
  date?: string;
  time?: string;
  phone?: string;
  createdAt?: string;
  status?: "pending" | "confirmed" | "cancelled" | "completed";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  rating?: number;
  price?: number;
  discountPrice?: number;
  productImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: CategoryReference;
  tags?: Array<string>;
};

export type MenuCategoriesReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "menuCategories";
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  menu?: MenuCategoriesReference;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle?: string;
  heroSubtitle?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroButtonText?: string;
  heroButtonLink?: string;
  aboutTitle?: string;
  aboutSubtitle?: string;
  aboutText?: string;
  testimonialAvatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  authorName?: string;
  position?: string;
  testimonialText?: string;
  aboutImages?: Array<{
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title?: string;
    _key: string;
  }>;
  menuCategories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  menu?: MenuCategoriesReference;
  discoverMenu?: Array<{
    title?: string;
    description?: string;
    price?: number;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
};

export type MenuCategories = {
  _id: string;
  _type: "menuCategories";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  items?: Array<{
    name?: string;
    description?: string;
    price?: string;
    isNew?: boolean;
    _type: "item";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Reservations
  | SanityImageAssetReference
  | CategoryReference
  | Product
  | MenuCategoriesReference
  | Category
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | HomePage
  | MenuCategories
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{  heroTitle,  heroSubtitle,  heroImage { asset->{ url } },  heroButtonText,  heroButtonLink}
export type HOME_PAGE_QUERY_RESULT = {
  heroTitle: string | null;
  heroSubtitle: string | null;
  heroImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  heroButtonText: string | null;
  heroButtonLink: string | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: WEEKLY_SPECIAL_QUERY
// Query: *[_type == "product" && "weekly-special" in tags][0]{  name,  rating,  price,  productImage { asset->{ url } },  tags,}
export type WEEKLY_SPECIAL_QUERY_RESULT = {
  name: string | null;
  rating: number | null;
  price: number | null;
  productImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  tags: Array<string> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: FEATURED_ABOUT_QUERY
// Query: *[_type == "homePage"][0]{  aboutTitle,  aboutSubtitle,  aboutText,  testimonialAvatar { asset->{ url } },  authorName,  position,  testimonialText,  aboutImages[] {    image { asset->{ url } },    title  }}
export type FEATURED_ABOUT_QUERY_RESULT = {
  aboutTitle: string | null;
  aboutSubtitle: string | null;
  aboutText: string | null;
  testimonialAvatar: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  authorName: string | null;
  position: string | null;
  testimonialText: string | null;
  aboutImages: Array<{
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    title: string | null;
  }> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: MENU_CATEGORY_QUERY
// Query: *[_type == "homePage"][0]{  menuCategories[]->{    _id,    title,    description,    "slug": slug.current,    image { asset->{ url } },    products[]->{      _id,      name,      price,      rating,      productImage { asset->{ url } },      tags    }  }}
export type MENU_CATEGORY_QUERY_RESULT = {
  menuCategories: Array<{
    _id: string;
    title: string | null;
    description: null;
    slug: string | null;
    image: null;
    products: null;
  }> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: MENU_QUERY
// Query: *[_type == "menuCategories"]{  _id,  title,  subtitle,  "slug": slug.current,  image { asset->{url} },  items[]{  _key,    name,    description,    price,    isNew  }}
export type MENU_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  subtitle: string | null;
  slug: string | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  items: Array<{
    _key: string;
    name: string | null;
    description: string | null;
    price: string | null;
    isNew: boolean | null;
  }> | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: DISCOVER_MENU_QUERY
// Query: *[_type == "homePage"][0]{  discoverMenu[]{    _key,    title,    description,    price,    image { asset->{url} }  }}
export type DISCOVER_MENU_QUERY_RESULT = {
  discoverMenu: Array<{
    _key: string;
    title: string | null;
    description: string | null;
    price: number | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  }> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: RESERVATIONS_QUERY
// Query: *[_type == "reservations"] | order(_createdAt desc){  _id,  guestCount,  name,  date,  time,  phone,  status,  createdAt,  _createdAt}
export type RESERVATIONS_QUERY_RESULT = Array<{
  _id: string;
  guestCount: number | null;
  name: string | null;
  date: string | null;
  time: string | null;
  phone: string | null;
  status: "cancelled" | "completed" | "confirmed" | "pending" | null;
  createdAt: string | null;
  _createdAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "homePage"][0]{\n  heroTitle,\n  heroSubtitle,\n  heroImage { asset->{ url } },\n  heroButtonText,\n  heroButtonLink\n}': HOME_PAGE_QUERY_RESULT;
    '*[_type == "product" && "weekly-special" in tags][0]{\n  name,\n  rating,\n  price,\n  productImage { asset->{ url } },\n  tags,\n}': WEEKLY_SPECIAL_QUERY_RESULT;
    '*[_type == "homePage"][0]{\n  aboutTitle,\n  aboutSubtitle,\n  aboutText,\n  testimonialAvatar { asset->{ url } },\n  authorName,\n  position,\n  testimonialText,\n  aboutImages[] {\n    image { asset->{ url } },\n    title\n  }\n}': FEATURED_ABOUT_QUERY_RESULT;
    '*[_type == "homePage"][0]{\n  menuCategories[]->{\n    _id,\n    title,\n    description,\n    "slug": slug.current,\n    image { asset->{ url } },\n    products[]->{\n      _id,\n      name,\n      price,\n      rating,\n      productImage { asset->{ url } },\n      tags\n    }\n  }\n}': MENU_CATEGORY_QUERY_RESULT;
    '*[_type == "menuCategories"]{\n  _id,\n  title,\n  subtitle,\n  "slug": slug.current,\n  image { asset->{url} },\n  items[]{\n  _key,\n    name,\n    description,\n    price,\n    isNew\n  }\n}': MENU_QUERY_RESULT;
    '*[_type == "homePage"][0]{\n  discoverMenu[]{\n    _key,\n    title,\n    description,\n    price,\n    image { asset->{url} }\n  }\n}': DISCOVER_MENU_QUERY_RESULT;
    '*[_type == "reservations"] | order(_createdAt desc){\n  _id,\n  guestCount,\n  name,\n  date,\n  time,\n  phone,\n  status,\n  createdAt,\n  _createdAt\n}': RESERVATIONS_QUERY_RESULT;
  }
}
